# Generated by Django 5.0.1 on 2024-01-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0003_actor_alter_genre_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("actor", models.ManyToManyField(to="theatre.actor")),
                ("genre", models.ManyToManyField(to="theatre.genre")),
            ],
            options={
                "ordering": ("title",),
            },
        ),
    ]
