# Generated by Django 5.0.1 on 2024-01-17 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0004_play"),
    ]

    operations = [
        migrations.RenameField(
            model_name="play",
            old_name="actor",
            new_name="actors",
        ),
        migrations.RenameField(
            model_name="play",
            old_name="genre",
            new_name="genres",
        ),
    ]
